"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase-browser";

type Project = { id: string; title: string; slug: string; skill: string; description: string; status: "draft"|"published"; featured: boolean; sort_order: number; cover_url?: string|null };
type Enquiry = { id: string; name: string; email: string; phone?: string; message: string; status: string; created_at?: string };
type Settings = Record<string,string>;

const starterProjects: Project[] = [
 {id:"fitzone",slug:"fitzone",title:"FITZONE",skill:"GYM & FITNESS",description:"Fitness brand identity, logo system, social creatives and promotional artwork.",status:"published",featured:true,sort_order:1},
 {id:"royal",slug:"royal",title:"ROYAL",skill:"LUXURY BRAND",description:"Luxury brand identity with premium gold-led visual direction and campaign graphics.",status:"published",featured:true,sort_order:2},
 {id:"music",slug:"music-festival",title:"MUSIC FESTIVAL",skill:"FESTIVAL",description:"Music festival posters, event graphics, social media creatives and promotional visuals.",status:"published",featured:true,sort_order:3},
 {id:"nature",slug:"nature",title:"NATURE",skill:"ORGANIC STORE",description:"Organic retail identity, packaging direction, promotional graphics and social content.",status:"published",featured:true,sort_order:4},
 {id:"coffee",slug:"coffee-house",title:"COFFEE HOUSE",skill:"HOUSE",description:"Coffee-house branding, menu graphics, campaign artwork and social media design.",status:"published",featured:true,sort_order:5},
 {id:"travel",slug:"travel",title:"TRAVEL",skill:"EXPLORE THE WORLD",description:"Travel campaign identity, destination graphics and digital promotional creatives.",status:"published",featured:true,sort_order:6},
];
const defaultSettings: Settings={name:"Siva Krishna",title:"Graphic Designer & Visual Creator",email:"skiamadesigner@gmail.com",whatsapp:"919908386188",location:"Hyderabad, Telangana, India",availability:"Available for selected projects",bio:"I help businesses and individuals stand out with creative, modern and impactful designs."};
const emptyProject={title:"",slug:"",skill:"",description:"",status:"draft" as "draft"|"published",featured:false,sort_order:10};

export default function AdminPage(){
 const supabase=useMemo(()=>createClient(),[]);
 const [tab,setTab]=useState("dashboard"),[projects,setProjects]=useState<Project[]>([]),[settings,setSettings]=useState<Settings>(defaultSettings),[enquiries,setEnquiries]=useState<Enquiry[]>([]);
 const [session,setSession]=useState<any>(null),[authChecked,setAuthChecked]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState(emptyProject),[editing,setEditing]=useState<string|null>(null);
 const supabaseReady=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);

 useEffect(()=>{supabase.auth.getSession().then(({data}:any)=>{setSession(data?.session??null);setAuthChecked(true)});const {data}:any=supabase.auth.onAuthStateChange((_e:any,s:any)=>setSession(s));return()=>data?.subscription?.unsubscribe?.()},[supabase]);
 useEffect(()=>{if(!session)return; (async()=>{const [{data:p},{data:s}]=await Promise.all([supabase.from("portfolio_projects").select("*").order("sort_order",{ascending:true}),supabase.from("site_settings").select("key,value")]);setProjects(p?.length?p:starterProjects);if(s?.length)setSettings({...defaultSettings,...Object.fromEntries(s.map((r:any)=>[r.key,typeof r.value==="string"?r.value:String(r.value??"")]))});})();},[session,supabase]);
 useEffect(()=>{if(tab!=="messages"||!session)return;supabase.from("contact_requests").select("*").order("created_at",{ascending:false}).then(({data}:any)=>setEnquiries(data??[]));},[tab,session,supabase]);

 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:"Signed in.");setBusy(false)};
 const logout=async()=>{await supabase.auth.signOut();setSession(null)};
 const saveProject=async()=>{setBusy(true);setMessage("");const slug=(form.slug||form.title).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const payload={...form,slug};let result:any;if(editing)result=await supabase.from("portfolio_projects").update(payload).eq("id",editing).select().single();else result=await supabase.from("portfolio_projects").insert(payload).select().single();if(result.error){setMessage(result.error.message)}else{setProjects(ps=>editing?ps.map(p=>p.id===editing?result.data:p):[...ps,result.data].sort((a,b)=>a.sort_order-b.sort_order));setForm(emptyProject);setEditing(null);setMessage("Project saved to Supabase.")}setBusy(false)};
 const togglePublish=async(p:Project)=>{const status=p.status==="published"?"draft":"published";const {error}=await supabase.from("portfolio_projects").update({status}).eq("id",p.id);if(!error)setProjects(ps=>ps.map(x=>x.id===p.id?{...x,status}:x));else setMessage(error.message)};
 const deleteProject=async(id:string)=>{if(!confirm("Delete this project?"))return;const {error}=await supabase.from("portfolio_projects").delete().eq("id",id);if(!error)setProjects(ps=>ps.filter(p=>p.id!==id));else setMessage(error.message)};
 const saveSettings=async()=>{setBusy(true);const rows=Object.entries(settings).map(([key,value])=>({key,value:JSON.stringify(value)}));const {error}=await supabase.from("site_settings").upsert(rows,{onConflict:"key"});setMessage(error?error.message:"Site settings saved to Supabase.");setBusy(false)};
 const updateEnquiry=async(id:string,status:string)=>{const {error}=await supabase.from("contact_requests").update({status}).eq("id",id);if(!error)setEnquiries(es=>es.map(e=>e.id===id?{...e,status}:e));else setMessage(error.message)};

 if(!authChecked)return <div className="admin-auth"><div className="admin-auth-card">Checking admin access…</div></div>;
 if(!session)return <div className="admin-auth"><form onSubmit={login} className="admin-auth-card"><img src="/logo.png" alt="SK"/><p className="eyebrow">SECURE CONTROL ROOM</p><h1>Admin Login</h1><p>Sign in with your Supabase admin account.</p><input type="email" required placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary-btn" disabled={busy}>{busy?"SIGNING IN…":"SIGN IN →"}</button>{message&&<small>{message}</small>}<Link href="/">← Back to portfolio</Link></form></div>;
 const published=projects.filter(p=>p.status==="published").length;
 const title=tab==="dashboard"?"Dashboard":tab==="projects"?"Portfolio Projects":tab==="settings"?"Site Settings":tab==="messages"?"Client Enquiries":"Appearance";
 return <div className="min-h-screen bg-[#02050b] text-white"><div className="mx-auto flex min-h-screen max-w-[1500px]">
  <aside className="hidden w-72 shrink-0 border-r border-white/10 bg-[#030913] p-6 lg:block"><Link href="/" className="flex items-center gap-3 border-b border-white/10 pb-6"><img src="/logo.png" alt="SK" className="h-12 w-12 rounded-full"/><span><b className="block text-cyan-300">SK</b><small className="tracking-[.25em] text-white/60">ADMIN</small></span></Link><nav className="mt-8 space-y-2">{[["dashboard","Dashboard"],["projects","Projects"],["settings","Site Settings"],["messages","Enquiries"],["appearance","Appearance"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`w-full rounded-xl px-4 py-3 text-left text-sm font-bold ${tab===id?"bg-blue-600/20 text-cyan-300 ring-1 ring-cyan-300/20":"text-white/60 hover:bg-white/5 hover:text-white"}`}>{label}</button>)}</nav><div className="mt-8 rounded-2xl border border-white/10 bg-black/20 p-4 text-xs text-white/45"><p className="font-bold text-white/80">Backend status</p><p className="mt-2">{supabaseReady?"● Supabase connected":"● Environment variables missing"}</p></div></aside>
  <main className="min-w-0 flex-1 p-5 sm:p-8"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.35em] text-cyan-300">SK DESIGNER / CONTROL ROOM</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{title}</h1></div><div className="flex gap-2"><Link href="/" className="rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-white/70">Open site</Link><button onClick={logout} className="rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-white/70">Logout</button></div></header>{message&&<div className="mb-5 rounded-xl border border-cyan-300/20 bg-cyan-300/5 px-4 py-3 text-xs text-cyan-100">{message}</div>}
   {tab==="dashboard"&&<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Published Projects",published],["Total Projects",projects.length],["Services",6],["Database",supabaseReady?"Online":"Setup needed"]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/10 bg-[#050b14] p-5"><p className="text-xs text-white/45">{l}</p><p className="mt-3 text-2xl font-black text-white">{v}</p></div>)}</section><section className="mt-5 rounded-2xl border border-white/10 bg-[#050b14] p-6"><p className="text-xs font-black tracking-[.3em] text-blue-400">BACKEND</p><h2 className="mt-3 text-xl font-black">Production data is connected</h2><p className="mt-2 text-sm text-white/50">Projects, site settings and client enquiries are stored in Supabase. Admin changes are protected by authenticated RLS policies.</p></section></>}
   {tab==="projects"&&<section className="space-y-5"><div className="rounded-2xl border border-white/10 bg-[#050b14] p-5"><p className="text-xs font-black tracking-[.3em] text-blue-400">PROJECT EDITOR</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input placeholder="Project title" value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/><input placeholder="Category / skill" value={form.skill} onChange={e=>setForm(f=>({...f,skill:e.target.value}))}/><input placeholder="Slug (optional)" value={form.slug} onChange={e=>setForm(f=>({...f,slug:e.target.value}))}/><input type="number" placeholder="Sort order" value={form.sort_order} onChange={e=>setForm(f=>({...f,sort_order:Number(e.target.value)}))}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} className="min-h-28 md:col-span-2"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.featured} onChange={e=>setForm(f=>({...f,featured:e.target.checked}))}/> Featured</label><select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value as any}))}><option value="draft">Draft</option><option value="published">Published</option></select></div><div className="mt-4 flex gap-2"><button onClick={saveProject} disabled={busy} className="primary-btn">{editing?"UPDATE PROJECT":"ADD PROJECT"}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(emptyProject)}} className="outline-btn">CANCEL</button>}</div></div>{projects.map(p=><article key={p.id} className="rounded-2xl border border-white/10 bg-[#050b14] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-black">{p.title}</h2><p className="mt-1 text-xs text-cyan-300">{p.skill} · {p.status.toUpperCase()}</p><p className="mt-2 text-xs text-white/45">{p.description}</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={()=>togglePublish(p)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{p.status==="published"?"Unpublish":"Publish"}</button><button onClick={()=>{setEditing(p.id);setForm({title:p.title,slug:p.slug,skill:p.skill,description:p.description,status:p.status,featured:p.featured,sort_order:p.sort_order})}} className="rounded-lg border border-cyan-300/20 px-3 py-2 text-xs text-cyan-200">Edit</button><button onClick={()=>deleteProject(p.id)} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-300">Delete</button></div></div></article>)}</section>}
   {tab==="settings"&&<section className="rounded-2xl border border-white/10 bg-[#050b14] p-6"><div className="grid gap-4 md:grid-cols-2">{Object.entries(settings).map(([key,value])=><label key={key} className="text-xs font-bold text-white/50">{key.replaceAll("_"," ").toUpperCase()}<input value={value} onChange={e=>setSettings(s=>({...s,[key]:e.target.value}))} className="mt-2 w-full"/></label>)}</div><button onClick={saveSettings} disabled={busy} className="mt-6 primary-btn">{busy?"SAVING…":"SAVE SITE SETTINGS"}</button></section>}
   {tab==="messages"&&<section className="space-y-3">{enquiries.length===0?<div className="rounded-2xl border border-white/10 bg-[#050b14] p-8 text-center"><h2 className="text-xl font-black">No enquiries yet</h2><p className="mt-2 text-sm text-white/45">New contact-form messages will appear here.</p></div>:enquiries.map(q=><article key={q.id} className="rounded-2xl border border-white/10 bg-[#050b14] p-5"><div className="flex flex-wrap justify-between gap-4"><div><b>{q.name}</b><a className="ml-3 text-xs text-cyan-300" href={`mailto:${q.email}`}>{q.email}</a><p className="mt-3 text-sm text-white/65">{q.message}</p><small className="mt-3 block text-white/30">{q.created_at?new Date(q.created_at).toLocaleString():""}</small></div><select value={q.status} onChange={e=>updateEnquiry(q.id,e.target.value)}><option>new</option><option>read</option><option>replied</option><option>archived</option></select></div></article>)}</section>}
   {tab==="appearance"&&<section className="rounded-2xl border border-white/10 bg-[#050b14] p-6"><p className="text-xs font-black tracking-[.3em] text-blue-400">CINEMATIC THEME</p><h2 className="mt-3 text-xl font-black">SK eye / neon paint direction</h2><p className="mt-2 text-sm text-white/50">The public site keeps the dark cinematic interface, electric blue accents and exact SK logo asset. Theme settings can be expanded later without changing the portfolio data.</p></section>}
  </main></div></div>;
}
